/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as LivrosRouteImport } from './routes/livros'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSlugRouteImport } from './routes/admin.$slug'
import { Route as AdminNovoRouteImport } from './routes/admin.novo'
import { Route as AtendimentosIndexRouteImport } from './routes/atendimentos.index'
import { Route as AtendimentosSlugRouteImport } from './routes/atendimentos.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as LivrosIndexRouteImport } from './routes/livros.index'
import { Route as LivrosSlugRouteImport } from './routes/livros.$slug'
import { Route as NovidadesIndexRouteImport } from './routes/novidades.index'
import { Route as NovidadesSlugRouteImport } from './routes/novidades.$slug'
import { Route as ApiPublicBlogImagemSplatRouteImport } from './routes/api/public/blog-imagem/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosRoute = LivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/admin/$slug',
  path: '/admin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNovoRoute = AdminNovoRouteImport.update({
  id: '/admin/novo',
  path: '/admin/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosIndexRoute = AtendimentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtendimentosRoute,
} as any)
const AtendimentosSlugRoute = AtendimentosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AtendimentosRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CursosRoute,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CursosRoute,
} as any)
const LivrosIndexRoute = LivrosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LivrosRoute,
} as any)
const LivrosSlugRoute = LivrosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LivrosRoute,
} as any)
const NovidadesIndexRoute = NovidadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovidadesRoute,
} as any)
const NovidadesSlugRoute = NovidadesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NovidadesRoute,
} as any)
const ApiPublicBlogImagemSplatRoute =
  ApiPublicBlogImagemSplatRouteImport.update({
    id: '/api/public/blog-imagem/$',
    path: '/api/public/blog-imagem/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRouteWithChildren
  '/livros': typeof LivrosRouteWithChildren
  '/novidades': typeof NovidadesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/novo': typeof AdminNovoRoute
  '/atendimentos/$slug': typeof AtendimentosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/livros/$slug': typeof LivrosSlugRoute
  '/novidades/$slug': typeof NovidadesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/atendimentos/': typeof AtendimentosIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/novidades/': typeof NovidadesIndexRoute
  '/api/public/blog-imagem/$': typeof ApiPublicBlogImagemSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/novo': typeof AdminNovoRoute
  '/atendimentos/$slug': typeof AtendimentosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/livros/$slug': typeof LivrosSlugRoute
  '/novidades/$slug': typeof NovidadesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/atendimentos': typeof AtendimentosIndexRoute
  '/blog': typeof BlogIndexRoute
  '/cursos': typeof CursosIndexRoute
  '/livros': typeof LivrosIndexRoute
  '/novidades': typeof NovidadesIndexRoute
  '/api/public/blog-imagem/$': typeof ApiPublicBlogImagemSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimentos': typeof AtendimentosRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRouteWithChildren
  '/livros': typeof LivrosRouteWithChildren
  '/novidades': typeof NovidadesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/novo': typeof AdminNovoRoute
  '/atendimentos/$slug': typeof AtendimentosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/livros/$slug': typeof LivrosSlugRoute
  '/novidades/$slug': typeof NovidadesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/atendimentos/': typeof AtendimentosIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/livros/': typeof LivrosIndexRoute
  '/novidades/': typeof NovidadesIndexRoute
  '/api/public/blog-imagem/$': typeof ApiPublicBlogImagemSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimentos'
    | '/blog'
    | '/contato'
    | '/cursos'
    | '/livros'
    | '/novidades'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/$slug'
    | '/admin/novo'
    | '/atendimentos/$slug'
    | '/blog/$slug'
    | '/cursos/$slug'
    | '/livros/$slug'
    | '/novidades/$slug'
    | '/admin/'
    | '/atendimentos/'
    | '/blog/'
    | '/cursos/'
    | '/livros/'
    | '/novidades/'
    | '/api/public/blog-imagem/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/$slug'
    | '/admin/novo'
    | '/atendimentos/$slug'
    | '/blog/$slug'
    | '/cursos/$slug'
    | '/livros/$slug'
    | '/novidades/$slug'
    | '/admin'
    | '/atendimentos'
    | '/blog'
    | '/cursos'
    | '/livros'
    | '/novidades'
    | '/api/public/blog-imagem/$'
  id:
    | '__root__'
    | '/'
    | '/atendimentos'
    | '/blog'
    | '/contato'
    | '/cursos'
    | '/livros'
    | '/novidades'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/$slug'
    | '/admin/novo'
    | '/atendimentos/$slug'
    | '/blog/$slug'
    | '/cursos/$slug'
    | '/livros/$slug'
    | '/novidades/$slug'
    | '/admin/'
    | '/atendimentos/'
    | '/blog/'
    | '/cursos/'
    | '/livros/'
    | '/novidades/'
    | '/api/public/blog-imagem/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentosRoute: typeof AtendimentosRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CursosRoute: typeof CursosRouteWithChildren
  LivrosRoute: typeof LivrosRouteWithChildren
  NovidadesRoute: typeof NovidadesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  AdminSlugRoute: typeof AdminSlugRoute
  AdminNovoRoute: typeof AdminNovoRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicBlogImagemSplatRoute: typeof ApiPublicBlogImagemSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros': {
      id: '/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof LivrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$slug': {
      id: '/admin/$slug'
      path: '/admin/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/novo': {
      id: '/admin/novo'
      path: '/admin/novo'
      fullPath: '/admin/novo'
      preLoaderRoute: typeof AdminNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos/': {
      id: '/atendimentos/'
      path: '/'
      fullPath: '/atendimentos/'
      preLoaderRoute: typeof AtendimentosIndexRouteImport
      parentRoute: typeof AtendimentosRoute
    }
    '/atendimentos/$slug': {
      id: '/atendimentos/$slug'
      path: '/$slug'
      fullPath: '/atendimentos/$slug'
      preLoaderRoute: typeof AtendimentosSlugRouteImport
      parentRoute: typeof AtendimentosRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof CursosRoute
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof CursosRoute
    }
    '/livros/': {
      id: '/livros/'
      path: '/'
      fullPath: '/livros/'
      preLoaderRoute: typeof LivrosIndexRouteImport
      parentRoute: typeof LivrosRoute
    }
    '/livros/$slug': {
      id: '/livros/$slug'
      path: '/$slug'
      fullPath: '/livros/$slug'
      preLoaderRoute: typeof LivrosSlugRouteImport
      parentRoute: typeof LivrosRoute
    }
    '/novidades/': {
      id: '/novidades/'
      path: '/'
      fullPath: '/novidades/'
      preLoaderRoute: typeof NovidadesIndexRouteImport
      parentRoute: typeof NovidadesRoute
    }
    '/novidades/$slug': {
      id: '/novidades/$slug'
      path: '/$slug'
      fullPath: '/novidades/$slug'
      preLoaderRoute: typeof NovidadesSlugRouteImport
      parentRoute: typeof NovidadesRoute
    }
    '/api/public/blog-imagem/$': {
      id: '/api/public/blog-imagem/$'
      path: '/api/public/blog-imagem/$'
      fullPath: '/api/public/blog-imagem/$'
      preLoaderRoute: typeof ApiPublicBlogImagemSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AtendimentosRouteChildren {
  AtendimentosSlugRoute: typeof AtendimentosSlugRoute
  AtendimentosIndexRoute: typeof AtendimentosIndexRoute
}

const AtendimentosRouteChildren: AtendimentosRouteChildren = {
  AtendimentosSlugRoute: AtendimentosSlugRoute,
  AtendimentosIndexRoute: AtendimentosIndexRoute,
}

const AtendimentosRouteWithChildren = AtendimentosRoute._addFileChildren(
  AtendimentosRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CursosRouteChildren {
  CursosSlugRoute: typeof CursosSlugRoute
  CursosIndexRoute: typeof CursosIndexRoute
}

const CursosRouteChildren: CursosRouteChildren = {
  CursosSlugRoute: CursosSlugRoute,
  CursosIndexRoute: CursosIndexRoute,
}

const CursosRouteWithChildren =
  CursosRoute._addFileChildren(CursosRouteChildren)

interface LivrosRouteChildren {
  LivrosSlugRoute: typeof LivrosSlugRoute
  LivrosIndexRoute: typeof LivrosIndexRoute
}

const LivrosRouteChildren: LivrosRouteChildren = {
  LivrosSlugRoute: LivrosSlugRoute,
  LivrosIndexRoute: LivrosIndexRoute,
}

const LivrosRouteWithChildren =
  LivrosRoute._addFileChildren(LivrosRouteChildren)

interface NovidadesRouteChildren {
  NovidadesSlugRoute: typeof NovidadesSlugRoute
  NovidadesIndexRoute: typeof NovidadesIndexRoute
}

const NovidadesRouteChildren: NovidadesRouteChildren = {
  NovidadesSlugRoute: NovidadesSlugRoute,
  NovidadesIndexRoute: NovidadesIndexRoute,
}

const NovidadesRouteWithChildren = NovidadesRoute._addFileChildren(
  NovidadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentosRoute: AtendimentosRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CursosRoute: CursosRouteWithChildren,
  LivrosRoute: LivrosRouteWithChildren,
  NovidadesRoute: NovidadesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  AdminSlugRoute: AdminSlugRoute,
  AdminNovoRoute: AdminNovoRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicBlogImagemSplatRoute: ApiPublicBlogImagemSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
